### PR TITLE
implement acts-as-favoritor

### PR DESCRIPTION
**Pull request by OlgaGabbert**
add gem acts-as-favoritor to like posts 
!issue: need to refresh to be able to see changes. 
could somebody review and update? thanks in advance!

### CODE REVIEW

**Comment by Klockzer** [comment]
@OlgaGabbert doesn't seem to work on my side, what is supposed to be the behavior?

**Comment by OlgaGabbert** [comment]
@Klockzer to be able to “like” you need to be logged-in, otherwise there is an error. Sorry, I’ve just noticed as I checked being a not a current_user. I’ll update it and add a screencast to my next commit to show the supposed behaviour

**Comment by Klockzer** [comment]
Basically, you click on the icon and then the color changed on the front and then the post will be marked as favorite on the backend? So the next step, will either to add a filter with your favorite post or/and having them in the user profil as well

**Comment by OlgaGabbert** [comment]
@Klockzer yes, for now only the color changes in frontend. do you think we might need an alert message to? like "saved"?

the changes will be saved to the backend and it would be easy to pull them to be able to show them for example in the users' profile (either the only thing for the "normal users" or alongside with the created posts for contributors). I'll use the gem for that. 
we could also implement the search function too and show only current_user.favorited_by_type('Post') if the user clicks the filter "favourites"

**Pull request merged**
